version: '3.5'

services:
  backend:
    image: docker.pkg.github.com/benjaminbini/poker-du-jeudi/poker-du-jeudi-back:latest
    build: ./backend
    ports:
      - "7777:8081"
    environment:
      - "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
    env_file: .env
    restart: always

  frontend:
    image: docker.pkg.github.com/benjaminbini/poker-du-jeudi/poker-du-jeudi-front:latest
    build: ./frontend
    ports:
      - "7778:80"
    restart: always