version: '3.5'

services:
  backend:
    build: ./backend
    ports:
      - "7777:8081"
    environment:
      - "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
    env_file: .env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "7778:80"
    restart: always