version: '3.5'

services:
  backend:
    build: ./backend
    ports:
      - "7777:8081"
    environment:
      - "SPRING_DATASOURCE_URL=${DATABASE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
  frontend:
    build: ./frontend-tailwind
    ports:
      - "7778:80"

