name: Build and deploy poker.bini.io

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          VUE_APP_API_BASE: ${{ secrets.VUE_APP_API_BASE }}
          VUE_APP_LOGIN_BASE: ${{ secrets.VUE_APP_LOGIN_BASE }}
        run: |
          touch .env
          echo VUE_APP_API_BASE=$VUE_APP_API_BASE >> frontend/.env.production
          echo VUE_APP_LOGIN_BASE=$VUE_APP_LOGIN_BASE >> frontend/.env.production
          docker-compose build
      - name: Push the image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker-compose push
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          envs: DATABASE_URL,DATABASE_USERNAME,DATABASE_PASSWORD,GITHUB_TOKEN,GITHUB_ACTOR,IMAGE_ID
          script: |
            echo "$GITHUB_TOKEN" | sudo docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
            sudo rm -rf /data/poker-du-jeudi
            sudo mkdir -p /data/poker-du-jeudi
            sudo chown deploy:deploy /data/poker-du-jeudi
            cd /data
            git clone https://github.com/${{ github.repository }}.git
            cd poker-du-jeudi
            echo SPRING_DATASOURCE_URL=$DATABASE_URL >> .env
            echo SPRING_DATASOURCE_USERNAME=$DATABASE_USERNAME >> .env
            echo SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD >> .env
            sudo docker-compose down
            sudo docker-compose rm
            sudo docker-compose up -d
